# CMake generated Testfile for 
# Source directory: C:/UMAP/uwot_pure_cpp
# Build directory: C:/UMAP/uwot_pure_cpp/build-test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(EnhancedWrapperTest "C:/UMAP/uwot_pure_cpp/build-test/Debug/test_enhanced_wrapper.exe")
  set_tests_properties(EnhancedWrapperTest PROPERTIES  _BACKTRACE_TRIPLES "C:/UMAP/uwot_pure_cpp/CMakeLists.txt;140;add_test;C:/UMAP/uwot_pure_cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(EnhancedWrapperTest "C:/UMAP/uwot_pure_cpp/build-test/Release/test_enhanced_wrapper.exe")
  set_tests_properties(EnhancedWrapperTest PROPERTIES  _BACKTRACE_TRIPLES "C:/UMAP/uwot_pure_cpp/CMakeLists.txt;140;add_test;C:/UMAP/uwot_pure_cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(EnhancedWrapperTest "C:/UMAP/uwot_pure_cpp/build-test/MinSizeRel/test_enhanced_wrapper.exe")
  set_tests_properties(EnhancedWrapperTest PROPERTIES  _BACKTRACE_TRIPLES "C:/UMAP/uwot_pure_cpp/CMakeLists.txt;140;add_test;C:/UMAP/uwot_pure_cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(EnhancedWrapperTest "C:/UMAP/uwot_pure_cpp/build-test/RelWithDebInfo/test_enhanced_wrapper.exe")
  set_tests_properties(EnhancedWrapperTest PROPERTIES  _BACKTRACE_TRIPLES "C:/UMAP/uwot_pure_cpp/CMakeLists.txt;140;add_test;C:/UMAP/uwot_pure_cpp/CMakeLists.txt;0;")
else()
  add_test(EnhancedWrapperTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(HNSWValidationTest "C:/UMAP/uwot_pure_cpp/build-test/Debug/hnsw_validation_test.exe")
  set_tests_properties(HNSWValidationTest PROPERTIES  _BACKTRACE_TRIPLES "C:/UMAP/uwot_pure_cpp/CMakeLists.txt;141;add_test;C:/UMAP/uwot_pure_cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(HNSWValidationTest "C:/UMAP/uwot_pure_cpp/build-test/Release/hnsw_validation_test.exe")
  set_tests_properties(HNSWValidationTest PROPERTIES  _BACKTRACE_TRIPLES "C:/UMAP/uwot_pure_cpp/CMakeLists.txt;141;add_test;C:/UMAP/uwot_pure_cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(HNSWValidationTest "C:/UMAP/uwot_pure_cpp/build-test/MinSizeRel/hnsw_validation_test.exe")
  set_tests_properties(HNSWValidationTest PROPERTIES  _BACKTRACE_TRIPLES "C:/UMAP/uwot_pure_cpp/CMakeLists.txt;141;add_test;C:/UMAP/uwot_pure_cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(HNSWValidationTest "C:/UMAP/uwot_pure_cpp/build-test/RelWithDebInfo/hnsw_validation_test.exe")
  set_tests_properties(HNSWValidationTest PROPERTIES  _BACKTRACE_TRIPLES "C:/UMAP/uwot_pure_cpp/CMakeLists.txt;141;add_test;C:/UMAP/uwot_pure_cpp/CMakeLists.txt;0;")
else()
  add_test(HNSWValidationTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ComprehensiveTest "C:/UMAP/uwot_pure_cpp/build-test/Debug/comprehensive_test.exe")
  set_tests_properties(ComprehensiveTest PROPERTIES  _BACKTRACE_TRIPLES "C:/UMAP/uwot_pure_cpp/CMakeLists.txt;142;add_test;C:/UMAP/uwot_pure_cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ComprehensiveTest "C:/UMAP/uwot_pure_cpp/build-test/Release/comprehensive_test.exe")
  set_tests_properties(ComprehensiveTest PROPERTIES  _BACKTRACE_TRIPLES "C:/UMAP/uwot_pure_cpp/CMakeLists.txt;142;add_test;C:/UMAP/uwot_pure_cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ComprehensiveTest "C:/UMAP/uwot_pure_cpp/build-test/MinSizeRel/comprehensive_test.exe")
  set_tests_properties(ComprehensiveTest PROPERTIES  _BACKTRACE_TRIPLES "C:/UMAP/uwot_pure_cpp/CMakeLists.txt;142;add_test;C:/UMAP/uwot_pure_cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ComprehensiveTest "C:/UMAP/uwot_pure_cpp/build-test/RelWithDebInfo/comprehensive_test.exe")
  set_tests_properties(ComprehensiveTest PROPERTIES  _BACKTRACE_TRIPLES "C:/UMAP/uwot_pure_cpp/CMakeLists.txt;142;add_test;C:/UMAP/uwot_pure_cpp/CMakeLists.txt;0;")
else()
  add_test(ComprehensiveTest NOT_AVAILABLE)
endif()
